services:
  beat:
    build:
      context: .
      dockerfile: ./docker/beat.Dockerfile
    volumes:
      - ./app:/app/
      - .env:/app/.env
    environment:
      REDIS_URL: redis
      RABBITMQ_URL: rabbitmq
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    depends_on:
      - rabbitmq
      - redis
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: ./docker/worker.Dockerfile
    volumes:
      - ./app:/app/
      - .env:/app/.env
    environment:
      REDIS_URL: redis
      RABBITMQ_URL: rabbitmq
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    depends_on:
      - rabbitmq
      - redis
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: webinars-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge